version: '3'

services:
  webserver:
    container_name: profile-manager
    image: csunmetalab/environment:alpha
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/

  composer:
    restart: 'no'
    container_name: profile-manager_composer
    image: composer:latest
    command: install --ignore-platform-reqs
    volumes:
      - .:/app/
